/* Automatically generated by './build/bin/build-entry.js' */

import Button from '../packages/button/index.js';
import Row from '../packages/row/index.js';
import Col from '../packages/col/index.js';
import SuperForm from '../packages/super-form/index.js';
import Container from '../packages/container/index.js';
import Header from '../packages/header/index.js';
import Aside from '../packages/aside/index.js';
import Main from '../packages/main/index.js';
import Footer from '../packages/footer/index.js';
import Grid from '../packages/grid/index.js';
import locale from 'main/locale';

const components = [
  Button,
  Row,
  Col,
  SuperForm,
  Container,
  Header,
  Aside,
  Main,
  Footer,
  Grid
];

const install = function(Vue, opts = {}) {
  locale.use(opts.locale);
  locale.i18n(opts.i18n);

  components.forEach(component => {
    Vue.component(component.name, component);
  });

  Vue.prototype.$ALBATRO = {
    size: opts.size || '',
    zIndex: opts.zIndex || 2000
  };
};

/* istanbul ignore if */
if (typeof window !== 'undefined' && window.Vue) {
  install(window.Vue);
}

export default {
  version: '0.1.0',
  locale: locale.use,
  i18n: locale.i18n,
  install,
  Button,
  Row,
  Col,
  SuperForm,
  Container,
  Header,
  Aside,
  Main,
  Footer,
  Grid
};
