/* Automatically generated by './build/bin/build-entry.ts' */

import Vue from "vue";
import AlButton from "~/button/index.ts";
import AlRow from "~/row/index.ts";
import AlCol from "~/col/index.ts";
import AlSuperForm from "~/super-form/index.ts";
import AlContainer from "~/container/index.ts";
import AlHeader from "~/header/index.ts";
import AlAside from "~/aside/index.ts";
import AlMain from "~/main/index.ts";
import AlFooter from "~/footer/index.ts";
import AlGrid from "~/grid/index.ts";
import AlTable from "~/table/index.ts";
import AlCollapse from "~/collapse/index.ts";
import AlCollapseItem from "~/collapse-item/index.ts";
import AlDialog from "~/dialog/index.ts";
import AlMessage from "~/message/index.ts";
import locale from "main/locale";
import AlCollapseTransition from "main/transitions/collapse-transition.js";

const components = [
  AlButton,
  AlRow,
  AlCol,
  AlSuperForm,
  AlContainer,
  AlHeader,
  AlAside,
  AlMain,
  AlFooter,
  AlGrid,
  AlTable,
  AlCollapse,
  AlCollapseItem,
  AlCollapseTransition
];

const install = function(vue: any, opts: any = {}) {
  locale.use(opts.locale);
  locale.i18n(opts.i18n);

  components.forEach((component: any) => {
    Vue.component(component.name, component);
  });

  Vue.prototype.$ALBATRO = {
    size: opts.size || "",
    zIndex: opts.zIndex || 2000
  };

  Vue.prototype.$dialog = AlDialog;
  Vue.prototype.$message = AlMessage;
};

export default {
  version: "0.1.0",
  locale: locale.use,
  i18n: locale.i18n,
  install,
  AlCollapseTransition,
  ...components
};
