/* Automatically generated by './build/bin/build-entry.ts' */
import Vue from "vue";
import AlButton from '~/button/index.ts';
import AlRow from '~/row/index.ts';
import AlCol from '~/col/index.ts';
import AlSuperForm from '~/super-form/index.ts';
import AlContainer from '~/container/index.ts';
import AlHeader from '~/header/index.ts';
import AlAside from '~/aside/index.ts';
import AlMain from '~/main/index.ts';
import AlFooter from '~/footer/index.ts';
import locale from 'main/locale';

const components = [
  AlButton,
  AlRow,
  AlCol,
  AlSuperForm,
  AlContainer,
  AlHeader,
  AlAside,
  AlMain,
  AlFooter
];

const install = function(vue: any, opts: any = {}) {
  locale.use(opts.locale);
  locale.i18n(opts.i18n);

  components.forEach(component => {
    Vue.component(component.name, component);
  });

  Vue.prototype.$ALBATRO = {
    size: opts.size || '',
    zIndex: opts.zIndex || 2000
  };
};

/* istanbul ignore if */
// if (typeof window !== 'undefined' && window.Vue) {
//   install(window.Vue);
// }

export default {
  version: '0.1.0',
  locale: locale.use,
  i18n: locale.i18n,
  install,
//{{list1}}
  ...components
};
